---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karate-app
  labels:
    app: karate-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karate-app
  template:
    metadata:
      labels:
        app: karate-app
    spec:
      containers:
      - name: karate-container
        image: 198011705618.dkr.ecr.us-east-1.amazonaws.com/karate-web@sha256:f0a8fd5016157fd84fec8cefddf8c8eb2a5475ed4d0a14ea4ba0e46b9efdfa85
        ports:
        - containerPort: 3000
...
